# -*- coding: utf-8 -*-
"""PROGETTO1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-mZucgjnfIBnsfYDQSG_6nTn-G2r_gA

BIBLIO SOFTWARE
"""

class Biblioteca:
    def __init__(self):
        self.libri = {}

    def aggiungi_libro(self, titolo, copie):
        if titolo in self.libri:
            self.libri[titolo] += copie
        else:
            self.libri[titolo] = copie
        print(f"Aggiunte {copie} copie di '{titolo}'.")

    def rimuovi_libro(self, titolo):
        if titolo in self.libri:
            del self.libri[titolo]
            print(f"Il libro '{titolo}' è stato rimosso.")
        else:
            print("Errore: il libro non esiste.")

    def verifica_disponibilita(self, titolo):
        return self.libri.get(titolo, 0) > 0

    def prendi_in_prestito(self, titolo):
        if self.verifica_disponibilita(titolo):
            self.libri[titolo] -= 1
            print(f"Hai preso in prestito '{titolo}'. Copie rimanenti: {self.libri[titolo]}")
        else:
            print("Errore: il libro non è disponibile.")

    def statistiche_biblioteca(self):
        totale_libri = len(self.libri)
        copie_totali = sum(self.libri.values())
        media_copie = copie_totali / totale_libri if totale_libri > 0 else 0
        return {
            "totale_libri": totale_libri,
            "copie_totali": copie_totali,
            "media_copie": media_copie
        }

    def visualizza_libri(self):
        if not self.libri:
            print("La biblioteca è vuota.")
        else:
            for titolo, copie in self.libri.items():
                print(f"{titolo}: {copie} copie")

    def restaurare_libro(self, titolo, copie):
        if titolo in self.libri:
            self.libri[titolo] += copie
            print(f"Ripristinate {copie} copie di '{titolo}'.")
        else:
            print("Errore: il libro non esiste.")


def main():
    biblioteca = Biblioteca()
    while True:
        comando = input("Inserisci comando: aggiungi, rimuovi, verifica, presta, statistiche, visualizza, restaura, esci: ").strip().lower()
        if comando == "esci":
            break
        elif comando == "aggiungi":
            titolo = input("Titolo: ")
            copie = int(input("Numero di copie: "))
            biblioteca.aggiungi_libro(titolo, copie)
        elif comando == "rimuovi":
            titolo = input("Titolo: ")
            biblioteca.rimuovi_libro(titolo)
        elif comando == "verifica":
            titolo = input("Titolo: ")
            print("Disponibile" if biblioteca.verifica_disponibilita(titolo) else "Non disponibile")
        elif comando == "presta":
            titolo = input("Titolo: ")
            biblioteca.prendi_in_prestito(titolo)
        elif comando == "statistiche":
            stats = biblioteca.statistiche_biblioteca()
            print(stats)
        elif comando == "visualizza":
            biblioteca.visualizza_libri()
        elif comando == "restaura":
            titolo = input("Titolo: ")
            copie = int(input("Numero di copie: "))
            biblioteca.restaurare_libro(titolo, copie)
        else:
            print("Comando non riconosciuto.")

if __name__ == "__main__":
    main()